### ISSUE TITLE
Change Readme heading

### ISSUE THREAD

**Issue by chrispsommers** [open-traffic-generator/model-viewer#1]
https://github.com/open-traffic-generator/model-viewer/tree/main/webapp#ixnetworkopenapi shows "IxnetworkOpenapi" as heading. Should refer to OpenTrafficGenerator Model Viewer web app.

**Comment by ajbalogh** [comment]
This repo is being superseded by an open source utility - https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/open-traffic-generator/models/master/artifacts/openapi.yaml
